### ISSUE TITLE
♻️ [Refactor] : 소셜로그인 완성에 따른 TODO 처리 및 코드 정리, 주석 추가.

### ISSUE THREAD

**Issue by programofktw** [TinU-Official/TinU-Server#71]
### 브랜치 이름 (Branch Name)

social-login-refactor

### 깃허브 이슈만 생성할까요?

- [X] 깃허브 이슈만 생성할래요

### 수정 내용(Description)

social 로그인 기능 완성에 따라 전체적인 코드 정리 및 개발 중 미결 사항 체크

### 시작 날짜 (Start Date)

2024-12-19

### 기한 (Due Date)

2024-12-19

### 체크리스트(Tasks)

- [x] 코드 전반적인 //TODO() 해결 여부 확인
- [x] 코드 해석 남기기.

### 참조(References)

- Reference1
